// This file used to be generated by Lovable. We've replaced the Lovable Cloud
// OAuth wiring with a lightweight shim that delegates OAuth to the local
// Supabase client. Keeping the same exported `lovable.auth.signInWithOAuth`
// shape prevents touching other call sites.

import { supabase } from "../supabase/client";
import type { Provider } from "@supabase/supabase-js";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: Provider, opts?: SignInOptions) => {
      // Map Lovable-style args to Supabase v2 client call. We use
      // signInWithOAuth which by default navigates the browser to the
      // provider's consent page. Supabase will handle the redirect back and
      // the app's existing auth code (supabase.auth.getSession / onAuthStateChange)
      // will pick up the returned session.

      const redirectTo = opts?.redirect_uri ?? window.location.origin;

      // Build `options` for Supabase. Supabase supports passing `queryParams`
      // (for login_hint) under `options` in the client.
      const options: Record<string, unknown> = { redirectTo };

      if (opts?.extraParams) {
        // Put any extra params into queryParams so things like `login_hint`
        // are preserved.
        options.queryParams = { ...opts.extraParams };
      }

      try {
        const res = await supabase.auth.signInWithOAuth({ provider, options });

        // Return a compatible-ish shape. Lovable returned { redirected, error, tokens }
        // while Supabase returns { data, error }. For redirect flows the browser
        // will navigate away so callers shouldn't rely on synchronous tokens.

        if (res.error) {
          return { error: res.error };
        }

        // If Supabase returns a URL to redirect the browser (some SDKs do), keep
        // returning that info so callers that expect a `redirected`-like flow
        // can handle it. Otherwise, return the data object.
        // Normalize to a small surface used by this app: { redirected?: boolean, data?: any, error?: any }
        return { redirected: false, data: res.data ?? null };
      } catch (err) {
        return { error: err instanceof Error ? err : new Error(String(err)) };
      }
    },
  },
};
