/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FoodRouteImport } from './routes/food'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as SellerSlugRouteImport } from './routes/seller.$slug'
import { Route as RentIdRouteImport } from './routes/rent_.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as FoodIdRouteImport } from './routes/food.$id'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedUploadRentalRouteImport } from './routes/_authenticated/upload-rental'
import { Route as AuthenticatedUploadProductRouteImport } from './routes/_authenticated/upload-product'
import { Route as AuthenticatedUploadNotesRequestRouteImport } from './routes/_authenticated/upload-notes-request'
import { Route as AuthenticatedUploadNotesRouteImport } from './routes/_authenticated/upload-notes'
import { Route as AuthenticatedUploadFoodRequestRouteImport } from './routes/_authenticated/upload-food-request'
import { Route as AuthenticatedUploadFoodRouteImport } from './routes/_authenticated/upload-food'
import { Route as AuthenticatedSellerProfileRouteImport } from './routes/_authenticated/seller-profile'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedRentalRequestsRouteImport } from './routes/_authenticated/rental-requests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotificationSettingsRouteImport } from './routes/_authenticated/notification-settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSlugRoute = SellerSlugRouteImport.update({
  id: '/seller/$slug',
  path: '/seller/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIdRoute = RentIdRouteImport.update({
  id: '/rent_/$id',
  path: '/rent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotesRoute,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoodRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRentalRoute =
  AuthenticatedUploadRentalRouteImport.update({
    id: '/upload-rental',
    path: '/upload-rental',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadProductRoute =
  AuthenticatedUploadProductRouteImport.update({
    id: '/upload-product',
    path: '/upload-product',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadNotesRequestRoute =
  AuthenticatedUploadNotesRequestRouteImport.update({
    id: '/upload-notes-request',
    path: '/upload-notes-request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadNotesRoute =
  AuthenticatedUploadNotesRouteImport.update({
    id: '/upload-notes',
    path: '/upload-notes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadFoodRequestRoute =
  AuthenticatedUploadFoodRequestRouteImport.update({
    id: '/upload-food-request',
    path: '/upload-food-request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadFoodRoute = AuthenticatedUploadFoodRouteImport.update({
  id: '/upload-food',
  path: '/upload-food',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellerProfileRoute =
  AuthenticatedSellerProfileRouteImport.update({
    id: '/seller-profile',
    path: '/seller-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRentalRequestsRoute =
  AuthenticatedRentalRequestsRouteImport.update({
    id: '/rental-requests',
    path: '/rental-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationSettingsRoute =
  AuthenticatedNotificationSettingsRouteImport.update({
    id: '/notification-settings',
    path: '/notification-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/food': typeof FoodRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/notes': typeof NotesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rental-requests': typeof AuthenticatedRentalRequestsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/seller-profile': typeof AuthenticatedSellerProfileRoute
  '/upload-food': typeof AuthenticatedUploadFoodRoute
  '/upload-food-request': typeof AuthenticatedUploadFoodRequestRoute
  '/upload-notes': typeof AuthenticatedUploadNotesRoute
  '/upload-notes-request': typeof AuthenticatedUploadNotesRequestRoute
  '/upload-product': typeof AuthenticatedUploadProductRoute
  '/upload-rental': typeof AuthenticatedUploadRentalRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/food/$id': typeof FoodIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rent/$id': typeof RentIdRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/rent/': typeof RentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/food': typeof FoodRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/notes': typeof NotesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rental-requests': typeof AuthenticatedRentalRequestsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/seller-profile': typeof AuthenticatedSellerProfileRoute
  '/upload-food': typeof AuthenticatedUploadFoodRoute
  '/upload-food-request': typeof AuthenticatedUploadFoodRequestRoute
  '/upload-notes': typeof AuthenticatedUploadNotesRoute
  '/upload-notes-request': typeof AuthenticatedUploadNotesRequestRoute
  '/upload-product': typeof AuthenticatedUploadProductRoute
  '/upload-rental': typeof AuthenticatedUploadRentalRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/food/$id': typeof FoodIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rent/$id': typeof RentIdRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/rent': typeof RentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/food': typeof FoodRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/notes': typeof NotesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rental-requests': typeof AuthenticatedRentalRequestsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/seller-profile': typeof AuthenticatedSellerProfileRoute
  '/_authenticated/upload-food': typeof AuthenticatedUploadFoodRoute
  '/_authenticated/upload-food-request': typeof AuthenticatedUploadFoodRequestRoute
  '/_authenticated/upload-notes': typeof AuthenticatedUploadNotesRoute
  '/_authenticated/upload-notes-request': typeof AuthenticatedUploadNotesRequestRoute
  '/_authenticated/upload-product': typeof AuthenticatedUploadProductRoute
  '/_authenticated/upload-rental': typeof AuthenticatedUploadRentalRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/food/$id': typeof FoodIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rent_/$id': typeof RentIdRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/rent/': typeof RentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/food'
    | '/login'
    | '/marketplace'
    | '/notes'
    | '/admin'
    | '/dashboard'
    | '/notification-settings'
    | '/notifications'
    | '/profile'
    | '/rental-requests'
    | '/requests'
    | '/seller-profile'
    | '/upload-food'
    | '/upload-food-request'
    | '/upload-notes'
    | '/upload-notes-request'
    | '/upload-product'
    | '/upload-rental'
    | '/wishlist'
    | '/food/$id'
    | '/notes/$id'
    | '/product/$id'
    | '/rent/$id'
    | '/seller/$slug'
    | '/rent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/food'
    | '/login'
    | '/marketplace'
    | '/notes'
    | '/admin'
    | '/dashboard'
    | '/notification-settings'
    | '/notifications'
    | '/profile'
    | '/rental-requests'
    | '/requests'
    | '/seller-profile'
    | '/upload-food'
    | '/upload-food-request'
    | '/upload-notes'
    | '/upload-notes-request'
    | '/upload-product'
    | '/upload-rental'
    | '/wishlist'
    | '/food/$id'
    | '/notes/$id'
    | '/product/$id'
    | '/rent/$id'
    | '/seller/$slug'
    | '/rent'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/complete-profile'
    | '/food'
    | '/login'
    | '/marketplace'
    | '/notes'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/notification-settings'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/rental-requests'
    | '/_authenticated/requests'
    | '/_authenticated/seller-profile'
    | '/_authenticated/upload-food'
    | '/_authenticated/upload-food-request'
    | '/_authenticated/upload-notes'
    | '/_authenticated/upload-notes-request'
    | '/_authenticated/upload-product'
    | '/_authenticated/upload-rental'
    | '/_authenticated/wishlist'
    | '/food/$id'
    | '/notes/$id'
    | '/product/$id'
    | '/rent_/$id'
    | '/seller/$slug'
    | '/rent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  FoodRoute: typeof FoodRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NotesRoute: typeof NotesRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
  RentIdRoute: typeof RentIdRoute
  SellerSlugRoute: typeof SellerSlugRoute
  RentIndexRoute: typeof RentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$slug': {
      id: '/seller/$slug'
      path: '/seller/$slug'
      fullPath: '/seller/$slug'
      preLoaderRoute: typeof SellerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent_/$id': {
      id: '/rent_/$id'
      path: '/rent/$id'
      fullPath: '/rent/$id'
      preLoaderRoute: typeof RentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof FoodRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-rental': {
      id: '/_authenticated/upload-rental'
      path: '/upload-rental'
      fullPath: '/upload-rental'
      preLoaderRoute: typeof AuthenticatedUploadRentalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-product': {
      id: '/_authenticated/upload-product'
      path: '/upload-product'
      fullPath: '/upload-product'
      preLoaderRoute: typeof AuthenticatedUploadProductRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-notes-request': {
      id: '/_authenticated/upload-notes-request'
      path: '/upload-notes-request'
      fullPath: '/upload-notes-request'
      preLoaderRoute: typeof AuthenticatedUploadNotesRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-notes': {
      id: '/_authenticated/upload-notes'
      path: '/upload-notes'
      fullPath: '/upload-notes'
      preLoaderRoute: typeof AuthenticatedUploadNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-food-request': {
      id: '/_authenticated/upload-food-request'
      path: '/upload-food-request'
      fullPath: '/upload-food-request'
      preLoaderRoute: typeof AuthenticatedUploadFoodRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-food': {
      id: '/_authenticated/upload-food'
      path: '/upload-food'
      fullPath: '/upload-food'
      preLoaderRoute: typeof AuthenticatedUploadFoodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller-profile': {
      id: '/_authenticated/seller-profile'
      path: '/seller-profile'
      fullPath: '/seller-profile'
      preLoaderRoute: typeof AuthenticatedSellerProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-requests': {
      id: '/_authenticated/rental-requests'
      path: '/rental-requests'
      fullPath: '/rental-requests'
      preLoaderRoute: typeof AuthenticatedRentalRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notification-settings': {
      id: '/_authenticated/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof AuthenticatedNotificationSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationSettingsRoute: typeof AuthenticatedNotificationSettingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRentalRequestsRoute: typeof AuthenticatedRentalRequestsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSellerProfileRoute: typeof AuthenticatedSellerProfileRoute
  AuthenticatedUploadFoodRoute: typeof AuthenticatedUploadFoodRoute
  AuthenticatedUploadFoodRequestRoute: typeof AuthenticatedUploadFoodRequestRoute
  AuthenticatedUploadNotesRoute: typeof AuthenticatedUploadNotesRoute
  AuthenticatedUploadNotesRequestRoute: typeof AuthenticatedUploadNotesRequestRoute
  AuthenticatedUploadProductRoute: typeof AuthenticatedUploadProductRoute
  AuthenticatedUploadRentalRoute: typeof AuthenticatedUploadRentalRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationSettingsRoute:
    AuthenticatedNotificationSettingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRentalRequestsRoute: AuthenticatedRentalRequestsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSellerProfileRoute: AuthenticatedSellerProfileRoute,
  AuthenticatedUploadFoodRoute: AuthenticatedUploadFoodRoute,
  AuthenticatedUploadFoodRequestRoute: AuthenticatedUploadFoodRequestRoute,
  AuthenticatedUploadNotesRoute: AuthenticatedUploadNotesRoute,
  AuthenticatedUploadNotesRequestRoute: AuthenticatedUploadNotesRequestRoute,
  AuthenticatedUploadProductRoute: AuthenticatedUploadProductRoute,
  AuthenticatedUploadRentalRoute: AuthenticatedUploadRentalRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface FoodRouteChildren {
  FoodIdRoute: typeof FoodIdRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodIdRoute: FoodIdRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

interface NotesRouteChildren {
  NotesIdRoute: typeof NotesIdRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesIdRoute: NotesIdRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  FoodRoute: FoodRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  NotesRoute: NotesRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
  RentIdRoute: RentIdRoute,
  SellerSlugRoute: SellerSlugRoute,
  RentIndexRoute: RentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
