// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient(): any {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Supabase client will be a noop stub.`;
    console.error(`[Supabase] ${message}`);

    // Return a stubbed client with minimal behavior so runtime code doesn't try to access
    // undefined properties. The methods return Promises that resolve with a descriptive error.
    const stubResponse = async () => ({ data: null, error: new Error(message) });

    const stubBuilder = () => ({
      select: () => ({
        eq: () => ({ order: () => ({ limit: () => stubResponse() }) }),
        order: () => ({ limit: () => stubResponse() }),
        limit: () => stubResponse(),
      }),
      eq: () => ({ order: () => ({ limit: () => stubResponse() }) }),
      order: () => ({ limit: () => stubResponse() }),
      limit: () => stubResponse(),
    });

    const stubClient = {
      from: (_table: string) => stubBuilder(),
      storage: {
        from: (_bucket: string) => ({
          getPublicUrl: (_path: string) => ({
            data: { publicUrl: "" },
          }),
        }),
      },
  } as unknown as any;

    return stubClient;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: typeof window !== "undefined",
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
